import 'package:cloud_firestore/cloud_firestore.dart';



Future storeNeighbourhoods()async{
  List<String> locations = [
    'Umm Al-Usoud',
    'Umm Al-Amad',
    'Umm al Kundum',
    'Um Rummanah',
    'Umm Shterat',
    'Umm Quseir',
    'Abu Al-Sous',
    'Abu Al-Nair',
    'Abu Alanda',
    'Abu Nsair',
    'Areinba Al Sharqiyah',
    'Areinba Al Gharbiyah',
    'Al-Amir Hamzah',
    'Al-Iman',
    'Bahath',
    'Baqa\'a Camp',
    'Al Bnayyat',
    'Al Bayader',
    'Al-Baida',
    'Al Gardens',
    'Al-Jabal Al-Akhdar',
    'Jubaiha',
    'Al-Jumayyil',
    'Al Jandaweel',
    'Al-Jweideh',
    'Al Jizah',
    'Al Hurryeh',
    'Al-Husnyeh',
    'Al Hummar',
    'Al-Humranyah',
    'Al-Khreim',
    'Al-Khaznah',
    'Alkhashafia',
    'Al-Khadra',
    'Al-Dmeenah',
    'Al-Dmenah',
    '1st Circle',
    '3rd Circle',
    '8th Circle',
    '2nd Circle',
    '5th Circle',
    '4th Circle',
    '7th Circle',
    '6th Circle',
    'Al-Diyar',
    'Al-Thra',
    'Al-Dhuheibah',
    'Al-Dhuheibah Al-Gharbiyah',
    'Dhuheibah Al-Sharqiyah',
    'Al Rabiah',
    'Al-Rabwa',
    'Al-Rjoum',
    'Al Rajeeb',
    'Al-Rajila',
    'Al Ridwan',
    'Al-Raqim',
    'Al Rawabi',
    'Al Rawnaq',
    'Al-Zafaran',
    'Al-Zamila',
    'Al-Zahra',
    'Al-Zaytouneh',
    'As Sarou',
    'Al Sahl',
    'Al Sina\'a',
    'Swefieh',
    'Al-Dia',
    'Al Tuneib',
    'Al-Thuheir',
    'Al-\'Al',
    'Abdali',
    'Al-Abdaliya',
    'Al-Adlyeh',
    'Al-Oroubah',
    'Al-Awdeh',
    'Al-Fuhais',
    'Al-Feisal',
    'Al Qastal',
    'Al-Qasabat',
    'Al-Qusour',
    'Al-Quneitirah',
    'Al Qwaismeh',
    'Al-Kutaifah',
    'Al Kursi',
    'Al Kamaliya',
    'Al-Kom Al-Sharqi',
    'Al-Kom Al-Gharbi',
    'Al Lubban',
    'Madonna',
    'Al-Mahatta',
    'Sports City',
    'Al-Marqab',
    'Al-Mustanada',
    'Al-Mushatta',
    'Al-Mashqar',
    'Al-Ma\'adi',
    'Al-Mugairat',
    'Al Muqabalain',
    "Al Manarah",
    "Al-Mansour",
    "Al-Muwaqqar",
    "Al-Nuqairah",
    "Al-Naharyah",
    "Al Hashmi Al Janobi",
    "Al Hashmi Al Shamali",
    "Al-Wehdat",
    "Al Yadudah",
    "Daheit Al Yasmeen",
    "Al-Yarmouk",
    "Um Uthaiena",
    "Um al Basateen",
    "Umm A-Dananir",
    "Umm Al-Rasas",
    "Um El Summaq",
    "Um Batma",
    "Umm Zuwaytinah",
    "Umm Nowarah",
    "Badr",
    "Badr Jdedeh",
    "Basman",
    "Bilal",
    "Birayn",
    "Tla' Ali",
    "Jawa",
    "Al Ashrafyeh",
    "Jabal Al-Taj",
    "Jabal Al-Jofah",
    "Jabal Al Hussain",
    "Jabal Al Zohor",
    "Jabal Al-Lweibdeh",
    "Jabal Al-Marrikh",
    "Jabal Al Nuzha",
    "Jabal Al Naser",
    "Jabal Al-Nathif",
    "Jabal Amman",
    "Jelul",
    "Hjar Al Nawabilseh",
    "Husban",
    "Hettin",
    "Howarah",
    "Hay Albarakeh",
    "Hay Alkhaledeen",
    "Hay Al Rahmanieh",
    "Hay Alsaleheen",
    "Al-Shabah",
    "Adan",
    "Hai Nazzal",
    "khan Al-Zabib",
    "Khirbet Sooq",
    "Khalda",
    "Dabouq",
    "Deir Ghbar",
    "Ras El Ain",
    "Rujm ash Shami",
    "Rajm Al-Shof",
    "Rajm Amesh",
    "Zabboud",
    "Zumlat al Ulya",
    "Zuwayza",
    "Zinat Al-Rubue",
    "Zeinab",
    "Salem",
    "Sahab",
    "Al Urdon Street",
    "University Street",
    "Medina Street",
    "Almih St",
    "Mecca Street",
    "Shafa Badran",
    "Shmaisani",
    "Safut",
    "Salihiyat Al-Abid",
    "Sufa",
    "Swelieh",
    "Dahiet Al Ameer Ali",
    "Dahiet Al-Istiqlal",
    "Daheit Al Aqsa",
    "Daheit Al Ameer Hasan",
    "Dahiet Al Ameer Rashed",
    "Daheit Al-Haj Hassan",
    "Dahiet Al Hussain",
    "Daheit Al Rasheed",
    "Dahiet Al-Rawda",
    "Dahiet Al-Nakheel",
    "Dab'a",
    "Tabarboor",
    "Airport Road - Manaseer Gs",
    "Airport Road - Dunes Bridge",
    "Airport Road - Madaba Bridge",
    "Tloo' Al-Misdar",
    "Abdoun",
    "Iraq Al Ameer",
    "Arjan",
    "Ayn Rbat",
    "Uyun Al-Dhib",
    "Qafor",
    "Mahes",
    "Marka",
    "Marj El Hamam",
    "Marj Al-Furs",
    "Mobes",
    "Naour",
    "Wadi Al Haddadeh",
    "Wadi Al-Srour",
    "Wadi El Seer",
    "Wadi Al-Tay",
    "Wadi Al-Eish",
    "Wadi Saqra",
    "Downtown",
    "Yajouz",
    "Other"
  ];

  for (int i=0;i<locations.length;i++){
    await FirebaseFirestore.instance.collection('cities').doc('slNUwXRYptbmjcdC68sy').collection('neighborhood').add({
      'name':locations[i]
    }).then((value){
      print('$i ${locations[i]} + ${value.path}');
    }).onError((error, stackTrace) {
      print('l error ${error.toString()}');
    });

  }
  print('location stored');
}